<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>JPasskeep Entries</title>
    <script type="text/javascript">
        $jquery;format="none"$
        $gibberish;format="none"$
        $jpasskeep;format="none"$
    </script>
    <style type="text/css">
        $css;format="none"$
    </style>
</head>
<body>
<div id="cipherBlock">
    <form id="cryptoForm" action="" method="post">
        <input id="cipherText" name="cipherText" type="hidden" value="$cipherText$" />
        <label for="key">Password</label>
        &nbsp;
        <input id="key" name="key" type="password" />
        &nbsp;
        <input type="submit" value="Go" />
    </form>
</div>
</body>
</html>
